NAME = "my_smartass"
API_ID = 0
API_HASH = ''

GROUP_IDS = [ "" ] # PLEASE PROVIDE GROUP IDS AS STRINGS. BOT WILL WATCH THIS GROUPS PUTTED IN ARRAY
PEER_ID_FOR_ADMIN = "" # THIS IS FOR GROUP OR USER ID. BOT WILL SEND NOTIFICATIONS THERE. AND RECEIVE COMMANDS FROM YOU THERE. DO NOT GIVE CHANNEL ID

ALLOW_PREPARING_GRAPHS = 1 # IF YOU DO NOT WANT TO FETCH ALL MESSAGES OF GROUPS. MAKE THIS 0. WE DO NEED TO FETCH ALL MESSAGES OF GROUPS TO MAKE GRAPHS
